version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: tuesday
      time: "13:00"
      timezone: Europe/Athens
    open-pull-requests-limit: 10
    labels:
      - dependencies
    ignore:
      - dependency-name: "escape-string-regexp"
        versions: [ "5.x" ]
      - dependency-name: "xo"
        versions: [ ">0.39" ]
