version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: tuesday
      time: "13:00"
      timezone: Europe/Athens
    open-pull-requests-limit: 10
    labels:
      - dependencies
