git:
  depth: 10

language: node_js

node_js:
  - "4"

script: npm run lint && node make travis

matrix:
  fast_finish: true

notifications:
  email:
    - joshua@mervine.net
    - bootstrap@maxcdn.com

cache:
  directories:
    - node_modules
