version: "{build}"

clone_depth: 10

environment:
  matrix:
    - platform: "x86"

install:
  - ps: Install-Product node "8" $env:platform
  - npm install

build: off

test_script:
  - node -v
  - npm -v
  - npm test

matrix:
  fast_finish: true

cache:
  - 'node_modules -> appveyor.yml,package.json,package-lock.json'
