port: 3333
theme: 1
siteurl: 'https://www.bootstrapcdn.com'
description: 'The recommended free CDN for Bootstrap, Font Awesome, Bootswatch and Bootstrap Icons.'
title_suffix: 'BootstrapCDN'
authors:
  inactive:
    - name: Justin Dorfman
      twitter: jdorfman
      url: 'https://twitter.com/jdorfman'
    - name: Joshua Mervine
      twitter: mervinej
      url: 'https://twitter.com/mervinej'
      work:
        text: Heroku
        url: 'https://www.heroku.com/'
    - name: XhmikosR
      twitter: XhmikosR
      url: 'https://xhmikosr.io/'
favicon:
  uri: /assets/img/favicons/favicon.ico
javascript:
  - name: jquery
    uri: 'https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js'
    sri: sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=
  - name: clipboardjs
    uri: /assets/js/vendor/clipboard.min.js
  - name: main
    uri: /assets/js/main.js
friends:
  - name: Cloudflare
    url: 'https://www.cloudflare.com/'
  - name: Fastly
    url: 'https://www.fastly.com/'
  - name: NS1
    url: 'https://ns1.com/'
  - name: BunnyCDN
    url: 'https://bunny.net/'
  - name: Dmitriy Akulov
    url: 'https://dakulov.com/'
redirects:
  - name: legacy
    from: /legacy/
    to: /legacy/bootstrap/
  - name: alpha
    from: /alpha/
    to: /
  - name: beta
    from: /beta/
    to: /
  - name: bootswatch4
    from: /bootswatch4/
    to: /bootswatch/
  - name: jobs
    from: /jobs/
    to: /
  - name: privacy-policy
    from: /privacy-policy/
    to: /
