integrations:
  - name: Adobe Dreamweaver
    img: /assets/img/integrations/dreamweaver.png
    plat: Adobe Dreamweaver
    url: 'https://helpx.adobe.com/dreamweaver/using/bootstrap.html'
  - name: freeCodeCamp
    img: /assets/img/integrations/freecodecamp.png
    plat: Node.js
    url: 'https://www.freecodecamp.org/challenges/use-responsive-design-with-bootstrap-fluid-containers'
  - name: Bootstrap 3 Snippets
    img: /assets/img/integrations/atom-bootstrap3.png
    plat: Atom
    url: 'https://atom.io/packages/atom-bootstrap3'
  - name: Bootstrap 3
    img: /assets/img/integrations/drupal-bootstrap3.png
    plat: Drupal
    url: 'https://www.drupal.org/project/bootstrap'
  - name: Freight
    img: /assets/img/integrations/sentry-freight.png
    plat: Python
    url: 'https://github.com/getsentry/freight'
  - name: Bootstrap NBM
    img: /assets/img/integrations/bootstrap-nbm.png
    plat: NetBeans
    url: 'https://www.davidsalter.co.uk/bootstrap-cdn-plugin-for-netbeans-release-1-1-0/'
  - name: BootstrapCDN WP
    img: /assets/img/integrations/bootstrapcdn-wp.png
    plat: WordPress
    url: 'https://wordpress.org/plugins/bootstrapcdn/'
  - name: Light Bootstrap Dashboard
    img: /assets/img/integrations/light-bootstrap-dashboard.png
    plat: WebPlatform
    url: 'https://www.creative-tim.com/product/light-bootstrap-dashboard'
  - name: Radix Theme
    img: /assets/img/integrations/radix-theme-drupal.png
    plat: Drupal
    url: 'https://www.drupal.org/project/radix'
  - name: Bootstrap 3 Sublime Plugin
    img: /assets/img/integrations/bs3-sublime-plugin.png
    plat: Sublime
    url: 'https://github.com/JasonMortonNZ/bs3-sublime-plugin'
  - name: Bootstrap 3 Jade Sublime Plugin
    img: /assets/img/integrations/bs3-jade-sublime-plugin.png
    plat: Sublime
    url: 'https://github.com/rs459/bootstrap3-jade-sublime-plugin'
  - name: Bootstrap Editor and Builder
    img: /assets/img/integrations/bootply.png
    plat: Bootply
    url: 'https://www.bootply.com/'
  - name: React-Bootstrap
    img: /assets/img/integrations/react-bootstrap.png
    plat: React
    url: 'https://react-bootstrap.github.io/'
