name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run nyc -- npm run mocha:no-functional

      - name: Run Coveralls
        run: npm run coveralls
        if: github.repository == 'MaxCDN/bootstrapcdn' && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
